# Generated by Django 2.2.1 on 2019-09-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('name', models.CharField(max_length=256)),
                ('time', models.IntegerField()),
                ('content', models.CharField(default='', max_length=3000)),
                ('record_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=256)),
            ],
        ),
    ]
