# Generated by Django 2.2.1 on 2019-09-02 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190902_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': '记录', 'verbose_name_plural': '记录'},
        ),
    ]
