# Generated by Django 2.2.1 on 2019-09-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190902_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
