# Generated by Django 2.2.1 on 2019-09-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190902_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
