# Generated by Django 2.2.4 on 2019-09-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='newimg_url',
            field=models.ImageField(default='SOME STRING', upload_to='static/img'),
        ),
    ]
