# Generated by Django 2.2.1 on 2019-09-07 15:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_img_newimg_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='img',
            options={'ordering': ['-c_time'], 'verbose_name': 'Img', 'verbose_name_plural': 'Imgs'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-record_id'], 'verbose_name': 'Record', 'verbose_name_plural': 'Records'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-c_time'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='img',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='img',
            name='newimg_url',
        ),
        migrations.AddField(
            model_name='img',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='img',
            name='cooked_url',
            field=models.ImageField(default='None', upload_to='static/img/cooked'),
        ),
        migrations.AddField(
            model_name='img',
            name='raw_url',
            field=models.ImageField(default='None', upload_to='static/img/raw'),
        ),
        migrations.AddField(
            model_name='img',
            name='username',
            field=models.CharField(default='', max_length=256),
        ),
    ]
