# Generated by Django 2.2.1 on 2019-09-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190907_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img',
            name='cooked_url',
        ),
        migrations.AddField(
            model_name='img',
            name='cook1_url',
            field=models.ImageField(default='None', upload_to='static/img/cook1'),
        ),
        migrations.AddField(
            model_name='img',
            name='cook2_url',
            field=models.ImageField(default='None', upload_to='static/img/cook2'),
        ),
    ]
