# Generated by Django 2.2.1 on 2019-09-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190907_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='cook1_url',
            field=models.CharField(default='None', max_length=2560),
        ),
        migrations.AlterField(
            model_name='img',
            name='cook2_url',
            field=models.CharField(default='None', max_length=2560),
        ),
    ]
