# Generated by Django 2.2.1 on 2019-09-07 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20190907_2146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
